services:
  web:
    restart: always
    build: .
    container_name: backend_fastapi
    command: ["/bin/bash", "/commands/run.sh"]
    environment:
      - LOG_LEVEL=debug
      - PYTHONPATH=/usr/src/fastapi
      - WATCHFILES_FORCE_POLLING=true
    ports:
      - "8000:8000"
    volumes:
      - ./src:/usr/src/fastapi
    networks:
      - fastapi_network

networks:
  fastapi_network:
    driver: bridge
